component_profile:
  title: Taverna Component Profile
  mime_type: application/vnd.taverna.component-profile+xml
  category: Blob

bioextract_server:
  title: BioExtract Server
  mime_type: application/xml
